### PR TITLE
Project EOL Notice

### PR DESCRIPTION
**Pull request by shawndwells**
All tasks/roles now incorporated into corporate content. EOL'ing and redirecting to upstream project.

### CODE REVIEW

**Comment by redhatrises** [comment]
Let's let this PR sit for a bit before merging.

**Comment by kevensen** [comment]
Sounds good to me.

**Comment by shawndwells** [comment]
@kevensen mostly wanted you to see the PR and discuss before merging. Are you OK with merging this now? 

The content would still be archived for those who use or want to refer back to it, and the readme would point to our authoritative sources. 

After some time has passed we can remove the repo... but want to give users ample time to realize the change, update docs and slide decks, etc.

**Comment by kevensen** [comment]
@shawndwells No discussion is necessary.  Merge and close at your discretion.  We will continue the work at https://github.com/fedoraredteam/compliant.

**Comment by shawndwells** [comment]
Thanks @kevensen. Merged.

However - continuing under the fedoraredteam/compliant only shuffles the issue. We already have content shipping for NIST 800-53; why not contribute to an already shipping, already supported project that reflects the official strategy of Red Hat, Fedora, and NIST?

**Pull request merged**
